spring.application.name=PC-Parts-Inventory
spring.datasource.url=jdbc:postgresql://localhost:5432/pc_parts_inventory
spring.datasource.username=pcparts_user
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true